version: '3.8'

services:
    nats1:
        image: nats:latest
        ports:
            - '4222:4222'
            - '8222:8222'
        volumes:
            - ./data/nat1:/data
        command:
            - '--name=nats1'
            - '--cluster_name=c1'
            - '--cluster=nats://nats1:6222'
            - '--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222'
            - '--http_port=8222'
            - '--js'
            - '--sd=/data'

    nats2:
        image: nats:latest
        ports:
            - '4223:4222'
            - '8223:8222'
        volumes:
            - ./data/nat2:/data
        command:
            - '--name=nats2'
            - '--cluster_name=c1'
            - '--cluster=nats://nats2:6222'
            - '--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222'
            - '--http_port=8222'
            - '--js'
            - '--sd=/data'

    nats3:
        image: nats:latest
        ports:
            - '4224:4222'
            - '8224:8222'
        volumes:
            - ./data/nat3:/data
        command:
            - '--name=nats3'
            - '--cluster_name=c1'
            - '--cluster=nats://nats3:6222'
            - '--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222'
            - '--http_port=8222'
            - '--js'
            - '--sd=/data'
